"""Gate coverage: recording, denominators, report, and the pytest flag."""

from __future__ import annotations

import numpy as np
import pytest
from qiskit import QuantumCircuit

import qlens
from qlens import coverage
from qlens.coverage import CircuitCoverage, _circuit_key, _compress


def bell() -> QuantumCircuit:
    qc = QuantumCircuit(2, name="bell")
    qc.h(0)
    qc.cx(0, 1)
    return qc


def three_gate() -> QuantumCircuit:
    qc = QuantumCircuit(2, name="ansatz")
    qc.h(0)
    qc.cx(0, 1)
    qc.z(1)
    return qc


def two_gate_prefix() -> QuantumCircuit:
    qc = QuantumCircuit(2, name="ansatz")
    qc.h(0)
    qc.cx(0, 1)
    return qc


# --- range compression -------------------------------------------------


@pytest.mark.parametrize(
    "positions, rendered",
    [
        ([], ""),
        ([4], "4"),
        ([1, 2, 3], "1-3"),
        ([0, 1, 3, 5, 6, 7], "0-1, 3, 5-7"),
        ([2, 4, 6], "2, 4, 6"),
    ],
)
def test_compress_renders_ranges(positions: list[int], rendered: str) -> None:
    assert _compress(positions) == rendered


# --- circuit key derivation -------------------------------------------


def test_explicit_label_wins() -> None:
    assert _circuit_key(bell(), "my-label") == "my-label"


def test_named_circuit_keys_on_its_name() -> None:
    assert _circuit_key(bell(), None) == "bell"


def test_autogenerated_name_is_kept_when_nothing_better_exists() -> None:
    # An unnamed Qiskit circuit gets a "circuit-<n>" name and no usable
    # qualname; keeping the name keeps distinct circuits distinct rather
    # than merging them all under the type. Grouping across tests is what
    # an explicit name or label= is for.
    qc = QuantumCircuit(1)
    assert _circuit_key(qc, None).startswith("circuit-")


def test_function_circuit_keys_on_qualname() -> None:
    def my_ansatz() -> None:  # pragma: no cover - only its name is read
        pass

    assert _circuit_key(my_ansatz, None) == "test_function_circuit_keys_on_qualname.<locals>.my_ansatz"


# --- recording within a session ---------------------------------------


def test_run_records_executed_positions_and_stamps_the_result() -> None:
    with coverage.session() as cov:
        result = qlens.run(bell())
        assert result.coverage_key == "bell"
    entry = cov.circuits["bell"]
    assert entry.gates == {0: "h", 1: "cx"}
    assert entry.executed == {0, 1}
    assert entry.checked_fraction == 0.0


def test_assertion_records_the_checked_position() -> None:
    with coverage.session() as cov:
        result = qlens.run(bell())
        qlens.assert_state(result, result.statevector_at(1), at=1)
    entry = cov.circuits["bell"]
    assert entry.asserted == {1}
    assert entry.unchecked == [0]
    assert entry.checked_fraction == 0.5


def test_default_at_checks_the_final_position() -> None:
    with coverage.session() as cov:
        result = qlens.run(bell())
        qlens.assert_state(result, result.final_statevector)
    assert cov.circuits["bell"].asserted == {1}


def test_out_of_range_at_is_ignored() -> None:
    with coverage.session() as cov:
        result = qlens.run(bell())
        # No gate at position 9; recording must not invent one.
        coverage.record_assertion(result, 9)
    assert cov.circuits["bell"].asserted == set()


# --- declared reference (run coverage) --------------------------------


def test_declared_reference_exposes_unrun_gates() -> None:
    with coverage.session() as cov:
        coverage.declare(three_gate(), label="ansatz")
        result = qlens.run(two_gate_prefix(), label="ansatz")
        qlens.assert_state(result, result.final_statevector, at=1)
    entry = cov.circuits["ansatz"]
    assert entry.declared is True
    assert entry.total == 3
    assert entry.unrun == [2]
    assert entry.run_fraction == pytest.approx(2 / 3)
    # position 1 checked, positions 0 (ran, unchecked); 2 never ran
    assert entry.unchecked == [0]


def test_declare_does_not_count_as_execution() -> None:
    with coverage.session() as cov:
        coverage.declare(bell(), label="bell")
    entry = cov.circuits["bell"]
    assert entry.executed == set()
    assert entry.run_fraction == 0.0


# --- no active session -------------------------------------------------


def test_run_and_assert_are_no_ops_without_a_session() -> None:
    result = qlens.run(bell())  # must not raise, must not stamp a key
    assert result.coverage_key is None
    qlens.assert_state(result, result.final_statevector)  # no session: fine


def test_report_without_a_session_raises() -> None:
    with pytest.raises(qlens.QlensError):
        coverage.report()


def test_declare_without_a_session_raises() -> None:
    with pytest.raises(qlens.QlensError):
        coverage.declare(bell())


# --- report rendering --------------------------------------------------


def test_report_totals_and_table() -> None:
    with coverage.session() as cov:
        r1 = qlens.run(bell())
        qlens.assert_state(r1, r1.statevector_at(1), at=1)
        r2 = qlens.run(three_gate(), label="ansatz")
        qlens.assert_state(r2, r2.statevector_at(2), at=2)
    report = cov.report()
    assert report.total_gates == 5
    # bell: 1 of 2 checked; ansatz: 1 of 3 checked -> 2 of 5
    assert report.checked_fraction == pytest.approx(2 / 5)

    table = report.table()
    assert "Qlens gate coverage" in table
    assert "Circuit" in table and "Run" in table and "Checked" in table
    assert "bell" in table and "ansatz" in table
    assert "TOTAL" in table

    payload = report.as_dict()
    assert payload["total_gates"] == 5
    labels = {c["label"] for c in payload["circuits"]}
    assert labels == {"bell", "ansatz"}


def test_empty_report_is_fully_covered_by_convention() -> None:
    with coverage.session() as cov:
        pass
    report = cov.report()
    assert report.run_fraction == 1.0
    assert report.checked_fraction == 1.0
    assert report.total_gates == 0


# --- nesting -----------------------------------------------------------


def test_inner_session_shadows_outer() -> None:
    with coverage.session() as outer:
        with coverage.session() as inner:
            qlens.run(bell())
        qlens.run(three_gate(), label="ansatz")
    assert set(inner.circuits) == {"bell"}
    assert set(outer.circuits) == {"ansatz"}


# --- pytest plugin end to end -----------------------------------------


def test_qlens_cov_flag_prints_a_report(pytester: pytest.Pytester) -> None:
    pytester.makepyfile(
        """
        import qlens
        from qiskit import QuantumCircuit

        def test_bell():
            qc = QuantumCircuit(2, name="bell")
            qc.h(0)
            qc.cx(0, 1)
            result = qlens.run(qc)
            qlens.assert_state(result, result.statevector_at(1), at=1)
        """
    )
    outcome = pytester.runpytest("--qlens-cov")
    outcome.assert_outcomes(passed=1)
    outcome.stdout.fnmatch_lines(["*Qlens gate coverage*", "*bell*"])


def test_no_flag_prints_no_report(pytester: pytest.Pytester) -> None:
    pytester.makepyfile(
        """
        import qlens
        from qiskit import QuantumCircuit

        def test_bell():
            qc = QuantumCircuit(2, name="bell")
            qc.h(0)
            result = qlens.run(qc)
        """
    )
    outcome = pytester.runpytest()
    outcome.assert_outcomes(passed=1)
    assert "Qlens gate coverage" not in outcome.stdout.str()


def test_circuit_coverage_defaults_are_empty() -> None:
    entry = CircuitCoverage("x")
    assert entry.total == 0
    assert entry.run_fraction == 1.0  # nothing to run is vacuously covered
    assert np.isclose(entry.checked_fraction, 1.0)
