"""Gate coverage: which gate positions a test suite runs and which it checks.

Two questions about a circuit's gates, answered over a whole test run:

* **Run** -- did the suite ever execute this gate position? Below 100% only
  when a reference circuit is declared (:func:`declare`) and some of its
  gates never ran, which is the classical-control-flow case: pin the full
  circuit, run the suite, see which branches went untouched.
* **Checked** -- did any ``assert_*`` validate the state at this position?
  This is the ordinary test-coverage reading, and it stays below 100%
  whenever a suite runs gates it never asserts on.

Coverage is scoped to a :func:`session`. Inside one, every :func:`qlens.run`
records the positions it executed, and every ``assert_*`` given the run's
result records the position it checked (its ``at=``, or the final position).
The pytest plugin opens a session for the whole run under ``--qlens-cov`` and
prints the report at the end; :func:`session` is the programmatic entry.

Coverage is keyed per circuit by a label: an explicit ``label=`` on
:func:`qlens.run`, else the circuit's own name (a Qiskit ``QuantumCircuit``
name, a PennyLane ``QNode`` function name), else its type. Positions are
matched by index, so a label should name one circuit shape; a builder whose
branches put different gates at the same index should pass distinct labels.
"""

from __future__ import annotations

import re
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass, field
from typing import Any

from qlens._errors import QlensError

__all__ = [
    "CircuitCoverage",
    "CoverageReport",
    "CoverageSession",
    "declare",
    "report",
    "session",
]

# Qiskit names an unnamed circuit "circuit-<n>"; that is not a useful key,
# so fall through to the builder function's name when one is available.
_AUTOGENERATED_NAME = re.compile(r"^circuit-\d+$")


def _circuit_key(circuit: Any, label: str | None) -> str:
    if label:
        return label
    name = getattr(circuit, "name", None)
    if isinstance(name, str) and name and not _AUTOGENERATED_NAME.match(name):
        return name
    # A PennyLane QNode wraps the user's quantum function as .func; a plain
    # builder is its own function. Either way __qualname__ names it.
    func = getattr(circuit, "func", circuit)
    qualname = getattr(func, "__qualname__", None) or getattr(func, "__name__", None)
    if isinstance(qualname, str) and qualname:
        return qualname
    if isinstance(name, str) and name:
        return name
    return type(circuit).__name__


def _gate_positions(result: Any) -> list[int]:
    """Executed gate positions of a run, dropping the initial-state marker."""
    return [s.position for s in result.snapshots if s.gate != "initial"]


def _compress(positions: list[int]) -> str:
    """Render sorted positions as coverage.py-style ranges: ``1-3, 7, 9-11``."""
    if not positions:
        return ""
    runs: list[tuple[int, int]] = []
    start = previous = positions[0]
    for position in positions[1:]:
        if position == previous + 1:
            previous = position
            continue
        runs.append((start, previous))
        start = previous = position
    runs.append((start, previous))
    return ", ".join(
        str(lo) if lo == hi else f"{lo}-{hi}" for lo, hi in runs
    )


@dataclass
class CircuitCoverage:
    """Run and check coverage for one circuit label within a session."""

    label: str
    gates: dict[int, str] = field(default_factory=dict)  # position -> gate name
    executed: set[int] = field(default_factory=set)
    asserted: set[int] = field(default_factory=set)
    declared: bool = False  # a reference circuit pinned the gate set

    @property
    def total(self) -> int:
        """Gate positions in the denominator (the declared or observed set)."""
        return len(self.gates)

    @property
    def unrun(self) -> list[int]:
        """Declared positions no run reached (empty without a declaration)."""
        return sorted(p for p in self.gates if p not in self.executed)

    @property
    def unchecked(self) -> list[int]:
        """Positions that ran but no assertion validated."""
        return sorted(p for p in self.gates if p in self.executed and p not in self.asserted)

    @property
    def run_fraction(self) -> float:
        if not self.gates:
            return 1.0
        return len(self.executed & self.gates.keys()) / len(self.gates)

    @property
    def checked_fraction(self) -> float:
        if not self.gates:
            return 1.0
        return len(self.asserted & self.gates.keys()) / len(self.gates)

    def as_dict(self) -> dict[str, Any]:
        return {
            "label": self.label,
            "gates": self.total,
            "declared": self.declared,
            "run": round(self.run_fraction, 4),
            "checked": round(self.checked_fraction, 4),
            "unrun": self.unrun,
            "unchecked": self.unchecked,
        }


@dataclass
class CoverageReport:
    """A session's coverage, ready to render or serialise."""

    circuits: tuple[CircuitCoverage, ...]

    @property
    def total_gates(self) -> int:
        return sum(c.total for c in self.circuits)

    @property
    def run_fraction(self) -> float:
        total = self.total_gates
        if total == 0:
            return 1.0
        ran = sum(len(c.executed & c.gates.keys()) for c in self.circuits)
        return ran / total

    @property
    def checked_fraction(self) -> float:
        total = self.total_gates
        if total == 0:
            return 1.0
        checked = sum(len(c.asserted & c.gates.keys()) for c in self.circuits)
        return checked / total

    def as_dict(self) -> dict[str, Any]:
        return {
            "circuits": [c.as_dict() for c in self.circuits],
            "total_gates": self.total_gates,
            "run": round(self.run_fraction, 4),
            "checked": round(self.checked_fraction, 4),
        }

    def table(self) -> str:
        """The report as a coverage.py-style fixed-width table."""
        rows = [
            (
                c.label,
                str(c.total),
                _percent(c.run_fraction),
                _percent(c.checked_fraction),
                _compress(c.unchecked),
            )
            for c in sorted(self.circuits, key=lambda c: c.label)
        ]
        headers = ("Circuit", "Gates", "Run", "Checked", "Unchecked")
        total_row = (
            "TOTAL",
            str(self.total_gates),
            _percent(self.run_fraction),
            _percent(self.checked_fraction),
            "",
        )
        widths = [
            max(len(headers[i]), len(total_row[i]), *(len(r[i]) for r in rows))
            if rows
            else max(len(headers[i]), len(total_row[i]))
            for i in range(len(headers))
        ]

        def line(cells: tuple[str, ...]) -> str:
            # Label and Unchecked left-aligned; numeric columns right-aligned.
            parts = [cells[0].ljust(widths[0])]
            parts += [cells[i].rjust(widths[i]) for i in range(1, 4)]
            parts.append(cells[4].ljust(widths[4]))
            return "  ".join(parts).rstrip()

        rule = "-" * (sum(widths) + 2 * (len(widths) - 1))
        body = [line(r) for r in rows]
        return "\n".join(
            ["Qlens gate coverage", "", line(headers), rule, *body, rule, line(total_row)]
        )


def _percent(fraction: float) -> str:
    return f"{fraction * 100:.0f}%"


class CoverageSession:
    """Accumulates run and check coverage while active."""

    def __init__(self) -> None:
        self.circuits: dict[str, CircuitCoverage] = {}

    def record_run(self, result: Any, circuit: Any, label: str | None = None) -> str:
        key = _circuit_key(circuit, label)
        entry = self.circuits.setdefault(key, CircuitCoverage(key))
        for snapshot in result.snapshots:
            if snapshot.gate == "initial":
                continue
            entry.gates.setdefault(snapshot.position, snapshot.gate)
            entry.executed.add(snapshot.position)
        result.coverage_key = key
        return key

    def record_assertion(self, result: Any, at: int | None) -> None:
        key = getattr(result, "coverage_key", None)
        if key is None:
            return
        entry = self.circuits.get(key)
        if entry is None:
            return
        positions = _gate_positions(result)
        if not positions:
            return
        if at is None:
            position = positions[-1]
        elif at < 0:
            try:
                position = positions[at]
            except IndexError:
                return
        else:
            position = at
        if position in entry.gates:
            entry.asserted.add(position)

    def declare(self, circuit: Any, *, label: str | None = None, args: tuple[Any, ...] = ()) -> str:
        """Pin a circuit's full gate set as the run denominator.

        Runs the circuit through its backend to read its gates without
        counting that read as test execution, so a later suite's ``Run``
        coverage measures against the whole circuit.
        """
        from qlens.backends import detect_backend

        result = detect_backend(circuit).run(circuit, args=args)
        key = _circuit_key(circuit, label)
        entry = self.circuits.setdefault(key, CircuitCoverage(key))
        for snapshot in result.snapshots:
            if snapshot.gate == "initial":
                continue
            entry.gates.setdefault(snapshot.position, snapshot.gate)
        entry.declared = True
        return key

    def report(self) -> CoverageReport:
        return CoverageReport(tuple(self.circuits.values()))


_sessions: list[CoverageSession] = []


def _current() -> CoverageSession | None:
    return _sessions[-1] if _sessions else None


def begin() -> CoverageSession:
    """Open a coverage session and make it the active one. Pair with :func:`end`."""
    opened = CoverageSession()
    _sessions.append(opened)
    return opened


def end(opened: CoverageSession) -> None:
    """Close a session opened with :func:`begin`. Idempotent."""
    if opened in _sessions:
        _sessions.remove(opened)


@contextmanager
def session() -> Iterator[CoverageSession]:
    """Record coverage for the ``run``/``assert_*`` calls made inside the block.

    ::

        with qlens.coverage.session() as cov:
            result = qlens.run(circuit)
            qlens.assert_state(result, expected, at=1)
        print(cov.report().table())
    """
    opened = begin()
    try:
        yield opened
    finally:
        end(opened)


def record_run(result: Any, circuit: Any, *, label: str | None = None) -> None:
    """Record a run's executed positions, if a session is active. Never raises."""
    active = _current()
    if active is None:
        return
    try:
        active.record_run(result, circuit, label)
    except Exception:
        return


def record_assertion(result: Any, at: int | None) -> None:
    """Record the position an assertion checked, if a session is active.

    No-op when nothing is recording or the result is not from a tracked run.
    Never raises: coverage bookkeeping must not break a passing assertion.
    """
    active = _current()
    if active is None:
        return
    try:
        active.record_assertion(result, at)
    except Exception:
        return


def declare(circuit: Any, *, label: str | None = None, args: tuple[Any, ...] = ()) -> str:
    """Pin a circuit's full gate set as the run denominator for the active session."""
    active = _current()
    if active is None:
        raise QlensError("coverage.declare() needs an active coverage.session()")
    return active.declare(circuit, label=label, args=args)


def report() -> CoverageReport:
    """The active session's report."""
    active = _current()
    if active is None:
        raise QlensError("no active coverage session; open one with coverage.session()")
    return active.report()
